#!/usr/bin/perl
#
#
#
use v5.10;

use Config::Tiny;
#use DBI;
#use MIME::Base64;
#use Frontier::Daemon;


use lib '/usr/share/alienvault-center/lib';

use AV::Log;
#set_output_descriptors_to_dev_null();
#use avparseconf;
use Avrepository;


# Program version (DO NOT TOUCH THIS)
my $VER = "1.0 release 1";
my $web = "http://www.alienvault.com";
my $dataserver = "http://data.alienvault.com";
my $current_version_alienvault ;
my $current_version_local ;
my $cversion = q{};
my $csubversion = q{};
my $csubsubversion = q{};
my $program_name = 'alienvault-update';
my $DEBUGLOG = 0;
my $dbinary = "dialog";
my $profesional_version = 0;
my $profesional_version3 = 0;
my $profesional_version4 = 0;
my $free_version = 0;
my $free_version3 = 0;
my $free_version4 = 0;
my $percent = 0;
my $dialog_active = 1;
my $upgrade = 0;
my $flag = q{};
my $arch = `uname -m` ; $arch =~ s/\n//g;
my $tmppath = "/usr/share/ossim-installer/temp";
my $feed = 0;
#my $vpre = 0;
#my $vpost = 0;
my $wget_useragent = q{};
my $alienvault_useragent = '/usr/bin/alienvault-useragent';
my $REL3=q{RELEASES};

#
# Error codes are defined in:
# alienvault-api/alienvault-api-scripts/api_core/lib/celerymethods/errors.py
# alienvault-ossim/ossim/www/av_center/data/sections/common/code_translation.php
#
my $ERROR_INSTANCE_RUNNING = 50;
my $ERROR_INVALID_SIGNATURE3 = 51;
my $ERROR_UNAVAILABLE_SIGNATURE3 = 52;
my $ERROR_INVALID_KEY = 53;
my $ERROR_INVALID_KEY_ALT = 54;
my $ERROR_INVALID_SIGNATURE4 = 55;
my $ERROR_UNAVAILABLE_SIGNATURE4 = 56;
my $ERROR_INVALID_SIGNATURE_FEED = 57;
my $ERROR_UNAVAILABLE_SIGNATURE_FEED = 58;
my $ERROR_HA_RUNNING = 59;

# function
sub main();             # main program body
sub parse_argv();       # requires defined %config
sub config_check();     # requires defined %configcolor;  # colours configuration
sub help();             # help(string: $helpCmd);
sub apt_status();
sub feed_update();


#
# MAIN
#  

sub main() {

#    my $running_instance = `ps -fea | grep $program_name | grep -v grep | grep -v ps | wc -l`;
    my $running_instance = `ps -feaww | grep "/usr/bin/perl /usr/bin/$program_name" | grep -v grep | grep -v ps | wc -l`;
    chomp $running_instance;
    if ( $running_instance > 1 ) {
        console_log("$program_name is already running ... exiting");
        exit $ERROR_INSTANCE_RUNNING;
    }

    my $ha_not_running = system("cl_status rscstatus > /dev/null 2>&1") >>8;
    if ( $ha_not_running == 0 ) {
        console_log("System running in HA mode. If you want to update your system, please stop the HA system by running alienvault-ha-assistant --stop, and then update.");
        exit $ERROR_HA_RUNNING;
    }

	console_log("Checking APT status");
	apt_status();

	my %sysconf = Avrepository::get_current_repository_info();

	#print $sysconf{'distro'};
	
	#my @response_msg = %sysconf;
	#$current_version_local = $response_msg[1];
	$current_version_local = $sysconf{'distro'};

	$cversion = $sysconf{'version'};
	$csubversion = $sysconf{'subversion'};
	$csubsubversion = $sysconf{'subsubversion'};

   	# product(free/pro/demo).version.subversion.subsubversion 
	$wget_useragent = "Wget.AVInt-$current_version_local.$cversion.$csubversion.$csubsubversion";
	$wget_useragent = "\"`$alienvault_useragent` WGET\"" if ( -x $alienvault_useragent);



#	$vpre = get_current_oct_version();

	system("mkdir $tmppath") if (! -d "$tmppath");

    if ( $feed == 1 ) {
        feed_update();
		console_log("Finished");
        exit 0;
    }


	## update
	console_log("Starting update");
			$flag = "-v" if ($VERBOSELOG == 1);
			my $script_name;

			my $fl = 0;
			if ($current_version_local eq "alienvault3-pro"){ $fl = 1;}
			if ($current_version_local eq "alienvault3"){ $fl = 1;}

			if ( $fl == 1 ){
				$script_name = "alienvault3_update-script";
			}else{
				$script_name = "alienvault4_update-script";
				#if ( $current_version_local eq "unstable-pro"){
				if ( $current_version_local eq "alienvault4-pro"){
					if ( ( $encoded // 0 ) == 1){ 
						$script_name = "alienvault4_encoded_update-script"; 
					}
					
					if ( ( $saqqara // 0 ) == 1){ 
						$script_name = "alienvault4_saqqara_update-script"; 
					}
						
				}
			}

			if ( -f "$tmppath/$script_name"){
				verbose_log("Delete $tmppath/$script_name");
				system("rm -rf $tmppath/$script_name");
			}
                        system("rm -rf $tmppath/$script_name.sig") if ( -f "$tmppath/$script_name.sig" );



			verbose_log("Download $tmppath/$script_name");
			#system("wget -U $wget_useragent -O $tmppath/$script_name $dataserver/RELEASES/$script_name");
			system("wget -U $wget_useragent -O $tmppath/$script_name $dataserver/$REL3/$script_name");

			if ( -s "$tmppath/$script_name" ){
				system("wget -U $wget_useragent -O $tmppath/$script_name.sig $dataserver/$REL3/$script_name.sig");
				if ( -s "$tmppath/$script_name.sig"){
					my $valid_sig = system("gpg --verify --keyring /etc/apt/trusted.gpg $tmppath/$script_name.sig");
					if ($valid_sig != 0) {
						say("Invalid signature for upgrade file $script_name");
						exit $ERROR_INVALID_SIGNATURE4;
					}
				} else {
					say("Signature not available for upgrade file $script_name");
					exit $ERROR_UNAVAILABLE_SIGNATURE4;
				}

				verbose_log("Exec: $tmppath/$script_name");
				$flag_processed = ( $flag // q{} );
				my $code_result = system("/bin/bash $tmppath/$script_name $flag_processed");
                                my $update_result = $code_result >> 8; 
                                if ($update_result != 0) {
                                    console_log("There was an error updating the system");
                                    exit $update_result;
                                }
                                    

				my $info_version_file="/etc/alienvault-center/alienvault-info-version";
				if ( -s "$info_version_file" ){
                			my @ivcontent = `cat $info_version_file`;
			                if (not map(/^Subsubversion:*/,@ivcontent)) {
						system("echo \"Subsubversion: N\" >> $info_version_file");
					}
				}else{
					#system("echo \"Product: alienvault4\" > $info_version_file");
					system("echo \"Product: $current_version_local\" > $info_version_file");
                                        system("echo \"Version: 4\" >> $info_version_file");
                                        system("echo \"Subversion: 1\" >> $info_version_file");
                                        system("echo \"Subsubversion: 0\" >> $info_version_file");
				}
				system("sed -i 's/^Version:.*/Version: 4/' $info_version_file");
				system("sed -i 's/^Subversion:.*/Subversion: 1/' $info_version_file");
				system("sed -i 's/^Subsubversion:.*/Subsubversion: 0/' $info_version_file");

			}

#			$vpost = get_current_oct_version();
			console_log("Finished");

}

	#
	# END MAIN
	#

# Parse and check arguments
parse_argv();
if (config_check()) {
        main();
}else {
        error("Configuration check failed.");
}

sub parse_argv() {

        # no arguments?
        #if ($#ARGV == -1) {
#               print "use --help or -h\n"
        #}

        # scan command line arguments
        foreach (@ARGV) {
                my @parms = split(/=/);
                #my @parms = split(//);
                if (($parms[0] eq "--help") || ($parms[0] eq "-h")) { help(); }
                elsif (($parms[0] eq "--console-log") || ($parms[0] eq "-c")) {$CONSOLELOG = 1;}
                elsif (($parms[0] eq "--verbose") || ($parms[0] eq "-v")) {$VERBOSELOG = 1; $CONSOLELOG = 1; $dialog_active = 0;}
                elsif (($parms[0] eq "--debug") || ($parms[0] eq "-d")) {$DEBUGLOG = 1; $dialog_active = 0;}
                elsif (($parms[0] eq "--quiet") || ($parms[0] eq "-q")) {$dialog_active = 0;}
                elsif (($parms[0] eq "--encoded") || ($parms[0] eq "-e")) {$encoded = 1;}
                elsif (($parms[0] eq "--saqqara") || ($parms[0] eq "-s")) {$saqqara = 1;}
                elsif ($parms[0] eq "--feed") {$feed = 1;}
                elsif (($parms[0] eq "--add_vpnnode") || ($parms[0] eq "-avpn")) {
                        if ($parms[1] eq "") { error("ip needed (example: --add_vpnnode=192.168.1.100");}
                        $config{'add_vpnnode'} = "$parms[1]";
                        $dialog_active = 0;
                        }
		elsif ($parms[0] eq "--upgrade") {
			say 'The OSSIM upgrade tool is no longer supported. Please contact support@alienvault.com for more information.';
                        exit 1;
		}
                elsif ($parms[0] eq "-uc" ) {
			say 'The OSSIM upgrade tool is no longer supported. Please contact support@alienvault.com for more information.';
                        exit 1;
                        }
                elsif (($parms[0] eq "--release") || ($parms[0] eq "-r")) {
                        if ($parms[1] eq "") { error("branch needed (example: --release=rc4.2.2");}
                        $config{'release'} = "$parms[1]";
			$REL3=qq{RELEASES_$config{'release'}};
                        $dialog_active = 0;
                        }
                else {
                        error("Unknown argument $_ from command line.");
                }

                undef @parms;
        }
}



sub config_check() {

	# Checks configuration validity
        my $noerror = 1;


        if ( $CONSOLELOG == 1 || $DEBUGLOG == 1 || $VERBOSELOG == 1 ) {
                console_log("Console log mode on");
                $dialog_active = 0;
        }

        if ((exists $config{'add_sensor'}) && (! exists $config{'add_sensor_name'})) {
                error("Please specify the name of the Sensor");
                $noerror = 1;
        }

        return $noerror;
}

sub help(){
print <<EOF;

$program_name $VER Help ($^O, perl $])

Usage examples:
  $program_name [options]

Command line options:

        --help (or -h)
          Displays this help message.

        --console-log (or -c)
          Enable logging of messages to console.

        --verbose (or -v)
          Enable verbose.

        --debug (or -d)
          Enable debug mode. (insane)

        --quiet (or -q)
          Quiet mode.

		--encoded (or -e)
		  Install alienvault-server especial version for encoding.
		
		--feed
		  Update packages from feed.

For more info, please visit $web

EOF
exit;
}

sub apt_status(){
	my $LCK=0;
	my $dpk_g=`which dpkg`;$dpk_g=~ s/\n//g;
	while (1) {
		if ( $LCK == 1 ) {
			console_log("Running 'dpkg --configure -a --force-confnew' to correct the problem");
			system("$dpk_g --configure -a --force-confnew");
			last;
		}
		# looking for 'E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.',
		# which can be obtained with simulate too
		my @aptstatus = `apt-get -s -d install ossim-cd-tools 2>&1`;
		if (map(/^E: dpkg was interrupted*/,@aptstatus)) {
			my $MSG=join('\n',@aptstatus);
			console_log("$MSG");
			$LCK=1;
		}else{
			last;
		}
	}
}

sub feed_update() {
    console_log("Updating packages from feed");

    my $script_name = "update_feed.sh";

    if ( -f "$tmppath/$script_name" ) {
        verbose_log("Delete $tmppath/$script_name");
        system("rm -rf $tmppath/$script_name");
    }

    verbose_log("Download $tmppath/$script_name");
    #system("wget -U $wget_useragent -O $tmppath/$script_name $dataserver/RELEASES/$script_name");
    system("wget -U $wget_useragent -O $tmppath/$script_name $dataserver/$REL3/$script_name");

    if ( -s "$tmppath/$script_name" ) {
        system("wget -U $wget_useragent -O $tmppath/$script_name.sig $dataserver/$REL3/$script_name.sig");
	if ( -s "$tmppath/$script_name.sig"){
            my $valid_sig = system("gpg --verify --keyring /etc/apt/trusted.gpg $tmppath/$script_name.sig");
	    if ($valid_sig != 0) {
		    say("Invalid signature for upgrade file $script_name");
		    exit $ERROR_INVALID_SIGNATURE_FEED;
	    }

            verbose_log("Exec: $tmppath/$script_name");
            system("/bin/bash $tmppath/$script_name");
	} else {
            say("Signature not available for upgrade file $script_name");
            exit $ERROR_UNAVAILABLE_SIGNATURE_FEED;
	}
    }

    console_log("Done.");
}



